version: "3.9"

services:
  db:
    container_name: db
    image: mysql:8.4.4
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment: # These are ONLY for the MySQL container setup
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}

  # api:
  #   build: .
  #   ports:
  #     - "${PORT}:${PORT}"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - db
  #   command: >
  #     sh -c "
  #       pnpm db:migrate &&
  #       npx nodemon -w /app/migrations -e sql -x 'pnpm db:migrate' &
  #       pnpm dev
  #     "

volumes:
  mysql_data:
